version: "3"
services:
  pert7:
    build: ./php
    image: pert7_php:latest
    container_name: pert7
    hostname: "project-akhir"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx_pert7:
    build: ./nginx
    image: nginx_pert7:latest
    container_name: nginx_pert7
    hostname: "nginx_pert7"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pert7
